name: worlkFlow
on: push
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Backend tests is passing"
  frontend:
    runs-on: ubuntu-latest
    needs : backend
    steps:
      - run: echo "Building frontend after backend success"





