name: worlkFlow
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  final:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: "ZeroOps Production"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: echo "Key length :${#API_KEY}"
      - run: pip install pytest
      - run: python -m pytest
      - run: echo "pipeline success"
